### ISSUE TITLE
Switch camera Advanced

### ISSUE THREAD

**Issue by hrupin** [triniwiz/fancy-webrtc-android#4]
Hello. 
Made very cool. Thank you very much.

I just can not figure out how to switch the camera. Based on Advanced

**Comment by triniwiz** [comment]
Since the api is similar to the browser base api one way is by setting the facingMode to `environment` when calling the `getUserMedia` [like this](https://github.com/triniwiz/fancy-webrtc-android/blob/master/app/src/main/java/co/fitcom/fancywebrtcdemo/Advanced.java#L216)

**Comment by hrupin** [comment]
Thank you very much for the answer.

I did this:
`
fun setUpUserMedia(typeVideo: String) {
        val video = HashMap<String, Any>()
        video.put("facingMode", typeVideo)
        ...
}
`
and make a call during a call - 
`setUpUserMedia("environment")` - but the camera does not switch.

what am I doing wrong?

Tried to implement as in MainActivity, but there at the time of webRTC? .AddLocalStream (localStream) - an error occurs:
  ! jni-> ExceptionCheck ()
webRTC E / JavaBinder: !!! FAILED BINDER TRANSACTION !!!

I would be very grateful for any help in this matter.

**Comment by triniwiz** [comment]
Oh so there are two versions v1 which mostly uses `FancyWebRTC` and v2 which follows the web api you can find the example for v2 [here](https://github.com/triniwiz/fancy-webrtc-android/blob/master/app/src/main/java/co/fitcom/fancywebrtcdemo/Advanced.java) also the demo-server is located [here](https://github.com/triniwiz/nativescript-webrtc/tree/master/demo-server)

**Comment by hrupin** [comment]
Does v2 have the ability to switch the camera during a call?

**Comment by hrupin** [comment]
I am again on - and am trying to implement the switching as you said. But switching does not occur. And how can I not understand what I'm doing wrong

**Comment by triniwiz** [comment]
I’ll see if I can add a simple api to help

**Comment by hrupin** [comment]
Thank you very much

**Comment by triniwiz** [comment]
You can do [this](https://github.com/triniwiz/fancy-webrtc-android/blob/master/app/src/main/java/co/fitcom/fancywebrtcdemo/Advanced.java#L238-L262) now 🙂

**Comment by hrupin** [comment]
Thank you very much, very helpful.
